apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-manual-pv 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2 # this depends on the storage class of your Kubernetes cluster. 
  hostPath:
    path: "/mnt/data"